---
title: "Title"
output: 
  html_document:
    toc: true
    toc_depth: 2
  bibliographys: references.bib
---

# Introduction Section

Package installation and imports:
```{r, message=FALSE, warning=FALSE}
library(GEOquery)
library(edgeR)
library(ggplot2)
library(reshape2)
```

Introduce Paper and dataset. we begin by improting.

```{r, message=FALSE}
data_set_geoid <- "GSE264108"
gse <- getGEO(data_set_geoid, GSEMatrix = FALSE)
gse@header$summary
```

There are two datasets assosciated with this paper, raw counts and normalized counts. We will be doing the normalization from scratch so we will be using the raw counts.

```{r, message=FALSE}
sfilenames <- getGEOSuppFiles(data_set_geoid, fetch_files = FALSE)

data_filename <- sfilenames$fname[1]

download_dir <- file.path(getwd())

if(!file.exists(file.path(download_dir,data_set_geoid, data_filename))){
  sfiles = getGEOSuppFiles(data_set_geoid,
                           baseDir = download_dir, 
                           fetch_files = TRUE)
}

tnbc_data <- read.table(
  file.path(download_dir,data_set_geoid,data_filename),
  header=TRUE,
  sep="\t",
  check.names=TRUE)
dim(tnbc_data)

```


```{r}
colnames(tnbc_data)
```

```{r}
list_of_sample <- gse@gsms
sample_type <- do.call(rbind, 
                        lapply(list_of_sample, FUN=function(x){
                          c(x@header$title,
                            x@header$characteristics_ch1,
                            x@header$treatment_protocol_ch1,
                            x@header$source_name_ch1)}))
sample_df <- as.data.frame(sample_type, stringsAsFactors = FALSE)
colnames(sample_df) <- c("sample", "sampleCondition", "cellType", "diseaseState", "treatmentProtocol", "sampleType")
```

```{r}
sample_df[,'sample'] <- gsub(sample_df[,'sample'],
                                pattern = "Neutrophils ",
                                replacement = "")
sample_df[,'sampleCondition'] <- gsub(sample_df[,'sampleCondition'],
                                             pattern = "tissue: ",
                                             replacement = "")
sample_df[,'cellType'] <- gsub(sample_df[,'cellType'],
                                       pattern = "cell type: ",
                                       replacement = "")
sample_df[,'diseaseState'] <- gsub(sample_df[,'diseaseState'],
                                    pattern = "disease state: ",
                                    replacement = "")

sample_df
```



```{r}
geo_accessions <- sapply(list_of_sample, function(x) x@header$geo_accession)
colnames(tnbc_data)[2:15] <- geo_accessions

tnbc_df <- data.frame(tnbc_data)
```


### Clean Data

```{r}
sample_dt <- data.table::data.table(sample_df)
sample_dt[, (count = .N), by = sample_dt$diseaseState]
```

```{r}
summary(tnbc_data[ , 2:15])
```


```{r}
min_num_samples <- 7
data_matrix <- as.matrix(tnbc_data[ , 2:15])
keep = rowSums(edgeR::cpm(data_matrix) >1) > min_num_samples
filtered_tnbc_data = data_matrix[keep,]
```


```{r}
dim(filtered_tnbc_data)
```

```{r}
summary(filtered_tnbc_data)
```

```{r}
data2plot <- log2(filtered_tnbc_data)
boxplot(data2plot, xlab = "Samples", ylab = "log2 TPM",
  las = 2, cex = 0.5, cex.lab = 0.5,
  cex.axis = 0.5, main = "RNASeq Samples")
#draw the median on each box plot
abline(h = median(apply(data2plot, 2, median)),
  col = "green", lwd = 0.6, lty = "dashed")

counts_density <- apply(log2(filtered_tnbc_data), 2, density)
  #calculate the limits across all the samples
  xlim <- 0; ylim <- 0
  for (i in 1:length(counts_density)) {
    xlim <- range(c(xlim, counts_density[[i]]$x));
    ylim <- range(c(ylim, counts_density[[i]]$y))
  }
  cols <- rainbow(length(counts_density))
  ltys <- rep(1, length(counts_density))
  #plot the first density plot to initialize the plot
  plot(counts_density[[1]], xlim=xlim, ylim=ylim, type="n",
    ylab="Smoothing density of log2-CPM",
    main="", cex.lab = 0.85)
  #plot each line
  for (i in 1:length(counts_density))
    lines(counts_density[[i]], col=cols[i], lty=ltys[i])
  #create legend
  legend("topright", colnames(data2plot),
    col=cols, lty=ltys, cex=0.75,
    border ="blue", text.col = "green4",
    merge = TRUE, bg = "gray90")

```

```{r}
d <- edgeR::DGEList(counts=filtered_tnbc_data, group=sample_dt$diseaseState)
d <- calcNormFactors(d)
normalized_counts <- cpm(d)
```


```{r}
data2plot <- log2(normalized_counts)
boxplot(data2plot, xlab = "Samples", ylab = "log2 TPM",
  las = 2, cex = 0.5, cex.lab = 0.5,
  cex.axis = 0.5, main = "RNASeq Samples")
#draw the median on each box plot
abline(h = median(apply(data2plot, 2, median)),
  col = "green", lwd = 0.6, lty = "dashed")

counts_density <- apply(log2(normalized_counts), 2, density)
  #calculate the limits across all the samples
  xlim <- 0; ylim <- 0
  for (i in 1:length(counts_density)) {
    xlim <- range(c(xlim, counts_density[[i]]$x));
    ylim <- range(c(ylim, counts_density[[i]]$y))
  }
  cols <- rainbow(length(counts_density))
  ltys <- rep(1, length(counts_density))
  #plot the first density plot to initialize the plot
  plot(counts_density[[1]], xlim=xlim, ylim=ylim, type="n",
    ylab="Smoothing density of log2-CPM",
    main="", cex.lab = 0.85)
  #plot each line
  for (i in 1:length(counts_density))
    lines(counts_density[[i]], col=cols[i], lty=ltys[i])
  #create legend
  legend("topright", colnames(data2plot),
    col=cols, lty=ltys, cex=0.75,
    border ="blue", text.col = "green4",
    merge = TRUE, bg = "gray90")
```


Nice separation of disease states!
```{r}
limma::plotMDS(d, labels=NULL, pch = 1,
               col = c("darkgreen","blue")[factor(sample_dt$diseaseState)])

legend("topright", 
       legend=levels(factor(sample_dt$diseaseState)),
  pch=c(1), col= c("darkgreen","blue"),title="Class",
  bty = 'n', cex = 0.75)
```

Dispersion
```{r}
model_design <- model.matrix(~sample_dt$diseaseState)
d <- estimateDisp(d, model_design)
plotBCV(d,col.tagwise = "black",col.common = "red",)
```

```{r}
plotMeanVar(d, show.raw.vars = TRUE,
show.tagwise.vars=TRUE, NBline=TRUE,
show.ave.raw.vars = TRUE,show.binned.common.disp.vars = TRUE)
```

### Identifier Mapping

```{r}


```




